export const FIND_CHARGES_REQUEST = "FIND_CHARGES_REQUEST";
export const FIND_CHARGES_SUCCESS = "FIND_CHARGES_SUCCESS";
export const FIND_CHARGES_FAILURE = "FIND_CHARGES_FAILURE";

export const FIND_CHARGE_REQUEST = "FIND_CHARGE_REQUEST";
export const FIND_CHARGE_SUCCESS = "FIND_CHARGE_SUCCESS";
export const FIND_CHARGE_FAILURE = "FIND_CHARGE_FAILURE";

export const DELETE_CHARGE_REQUEST = "DELETE_CHARGE_REQUEST";
export const DELETE_CHARGE_SUCCESS = "DELETE_CHARGE_SUCCESS";
export const DELETE_CHARGE_FAILURE = "DELETE_CHARGE_FAILURE";

export const SAVE_CHARGE_REQUEST = "SAVE_CHARGE_REQUEST";
export const SAVE_CHARGE_SUCCESS = "SAVE_CHARGE_SUCCESS";
export const SAVE_CHARGE_FAILURE = "SAVE_CHARGE_FAILURE";
