export const FIND_PARTNERS_REQUEST = "FIND_PARTNERS_REQUEST";
export const FIND_PARTNERS_SUCCESS = "FIND_PARTNERS_SUCCESS";
export const FIND_PARTNERS_FAILURE = "FIND_PARTNERS_FAILURE";

export const FIND_PARTNER_REQUEST = "FIND_PARTNER_REQUEST";
export const FIND_PARTNER_SUCCESS = "FIND_PARTNER_SUCCESS";
export const FIND_PARTNER_FAILURE = "FIND_PARTNER_FAILURE";

export const DELETE_PARTNER_REQUEST = "DELETE_PARTNER_REQUEST";
export const DELETE_PARTNER_SUCCESS = "DELETE_PARTNER_SUCCESS";
export const DELETE_PARTNER_FAILURE = "DELETE_PARTNER_FAILURE";

export const SAVE_PARTNER_REQUEST = "SAVE_PARTNER_REQUEST";
export const SAVE_PARTNER_SUCCESS = "SAVE_PARTNER_SUCCESS";
export const SAVE_PARTNER_FAILURE = "SAVE_PARTNER_FAILURE";
