export const FIND_PENDINGITEMS_REQUEST = "FIND_PENDINGITEMS_REQUEST";
export const FIND_PENDINGITEMS_SUCCESS = "FIND_PENDINGITEMS_SUCCESS";
export const FIND_PENDINGITEMS_FAILURE = "FIND_PENDINGITEMS_FAILURE";

export const FIND_PENDINGITEM_REQUEST = "FIND_PENDINGITEM_REQUEST";
export const FIND_PENDINGITEM_SUCCESS = "FIND_PENDINGITEM_SUCCESS";
export const FIND_PENDINGITEM_FAILURE = "FIND_PENDINGITEM_FAILURE";

export const DELETE_PENDINGITEM_REQUEST = "DELETE_PENDINGITEM_REQUEST";
export const DELETE_PENDINGITEM_SUCCESS = "DELETE_PENDINGITEM_SUCCESS";
export const DELETE_PENDINGITEM_FAILURE = "DELETE_PENDINGITEM_FAILURE";

export const SAVE_PENDINGITEM_REQUEST = "SAVE_PENDINGITEM_REQUEST";
export const SAVE_PENDINGITEM_SUCCESS = "SAVE_PENDINGITEM_SUCCESS";
export const SAVE_PENDINGITEM_FAILURE = "SAVE_PENDINGITEM_FAILURE";
