export const FIND_RENTS_REQUEST = "FIND_RENTS_REQUEST";
export const FIND_RENTS_SUCCESS = "FIND_RENTS_SUCCESS";
export const FIND_RENTS_FAILURE = "FIND_RENTS_FAILURE";

export const FIND_RENT_REQUEST = "FIND_RENT_REQUEST";
export const FIND_RENT_SUCCESS = "FIND_RENT_SUCCESS";
export const FIND_RENT_FAILURE = "FIND_RENT_FAILURE";

export const DELETE_RENT_REQUEST = "DELETE_RENT_REQUEST";
export const DELETE_RENT_SUCCESS = "DELETE_RENT_SUCCESS";
export const DELETE_RENT_FAILURE = "DELETE_RENT_FAILURE";

export const SAVE_RENT_REQUEST = "SAVE_RENT_REQUEST";
export const SAVE_RENT_SUCCESS = "SAVE_RENT_SUCCESS";
export const SAVE_RENT_FAILURE = "SAVE_RENT_FAILURE";
