export const FIND_TRANSACTIONS_REQUEST = "FIND_TRANSACTIONS_REQUEST";
export const FIND_TRANSACTIONS_SUCCESS = "FIND_TRANSACTIONS_SUCCESS";
export const FIND_TRANSACTIONS_FAILURE = "FIND_TRANSACTIONS_FAILURE";

export const FIND_TRANSACTION_REQUEST = "FIND_TRANSACTION_REQUEST";
export const FIND_TRANSACTION_SUCCESS = "FIND_TRANSACTION_SUCCESS";
export const FIND_TRANSACTION_FAILURE = "FIND_TRANSACTION_FAILURE";

export const DELETE_TRANSACTION_REQUEST = "DELETE_TRANSACTION_REQUEST";
export const DELETE_TRANSACTION_SUCCESS = "DELETE_TRANSACTION_SUCCESS";
export const DELETE_TRANSACTION_FAILURE = "DELETE_TRANSACTION_FAILURE";

export const SAVE_TRANSACTION_REQUEST = "SAVE_TRANSACTION_REQUEST";
export const SAVE_TRANSACTION_SUCCESS = "SAVE_TRANSACTION_SUCCESS";
export const SAVE_TRANSACTION_FAILURE = "SAVE_TRANSACTION_FAILURE";
